### ISSUE TITLE
about the dataset

### ISSUE THREAD

**Issue by zyhrainbow** [Algolzw/daclip-uir#11]
Can you provide the dataset? thanks~

**Comment by Algolzw** [comment]
Sure, but the training data is too large to share thus we currently only provide the validation dataset [here](https://drive.google.com/file/d/1JKd1tA7rMoEbI9190daJqL7i6V1L8KUd/view?usp=sharing). 

We'll release all dataset links later and would like you to download them separately according to your requirements. To train the DA-CLIP, we also provide a [script](https://github.com/Algolzw/daclip-uir/blob/main/da-clip/README.md#create-dataset) to build the csv file with clean captions and degradation types.

**Comment by Algolzw** [comment]
Dataset links have been updated. :-)
