### ISSUE TITLE
About training

### ISSUE THREAD

**Issue by Iceeteeea** [Algolzw/daclip-uir#14]
感谢作者的这篇优秀工作。我在复现的时候遇到一个问题。在训练过程中的验证阶段会爆显存，可以通过修改参数来避免爆显存吗
![屏幕截图 2023-11-25 233658](https://github.com/Algolzw/daclip-uir/assets/46436527/c57ad3e9-be03-4f70-a080-968a88ab457f)

**Comment by Iceeteeea** [comment]
谢谢，我头一次碰到训练没问题但验证爆显存的情况，有点懵😵

**Comment by Algolzw** [comment]
因为训练用的是小patch size而测试会使用大很多的size（如deblurring中训练使用256但测试可能会大于1000）。像很多图像复原的方法会使用patch-based复原再组合成最终大图，但这样会有一些artifacts。

特别是我们code里使用了cross-attention，这个使得尺寸的影响更大。

**Comment by Iceeteeea** [comment]
谢谢回复，我理解了🫡
