### ISSUE TITLE
some question about paper

### ISSUE THREAD

**Issue by cslvjt** [Algolzw/daclip-uir#24]
Thank you for your excellent work. I have a question about the content of your paper. What does gradient flow(in Fig.2a)  mean and what does it do? I can't find its meaning elsewhere in the paper.

**Comment by cslvjt** [comment]
![image](https://github.com/Algolzw/daclip-uir/assets/65208601/520ab703-27a2-4b82-b722-ed91f9aed847)

As the paper says, $e_d^{I}$ represent degenerate types. Then when you use the degradation type as a conditional constraint, the model should generate a degraded image.

**Comment by Algolzw** [comment]
Hi! 

The gradient flow means the gradient backpropagation path (thanks for pointing it out, we will make it clear in the paper). Moreover, the degenerate type is used to specify image restoration tasks and we use the content embedding (which matches the clean caption) to guide the model to generate clean images.

**Comment by cslvjt** [comment]
Thank you
