### ISSUE TITLE
How to use latest robust model

### ISSUE THREAD

**Issue by ale93111** [Algolzw/daclip-uir#25]
Hi, thank you very much for your research it is very interesting.
i was wondering how to use the latest model as the old code doesn't work with it

checkpoint = 'pretrained/daclip_ViT-B-32_mix.pt'
model, preprocess = open_clip.create_model_from_pretrained('daclip_ViT-B-32', pretrained=checkpoint)

it cannot load the model because it gives an error
thank you!

**Comment by sunzhe09** [comment]
+1

**Comment by Algolzw** [comment]
Hi, which code were you running? I've tried the [app.py](https://github.com/Algolzw/daclip-uir/blob/d16309bb17f2c9c702e558ac756397e661aa1a52/universal-image-restoration/config/daclip-sde/app.py) and it looks work well.

**Comment by Algolzw** [comment]
Moreover, our project hasn't been merged into the official open_clip repo. Thus you probably should use our [open_clip](https://github.com/Algolzw/daclip-uir/tree/d16309bb17f2c9c702e558ac756397e661aa1a52/universal-image-restoration/open_clip) that contains the modified code for our DA-CLIP.

**Comment by ale93111** [comment]
using the correct open_clip was indeed the issue, thank you!
