### ISSUE TITLE
How to test using mutiple GPUs？

### ISSUE THREAD

**Issue by gorgeousmwz** [Algolzw/daclip-uir#33]
![image](https://github.com/Algolzw/daclip-uir/assets/102034314/1fd0a756-bac8-4f23-9451-f697a5281176)

The config in test.yml doesn't work.

**Comment by Algolzw** [comment]
Hi, our code only supports single GPU testing. :(
If you want to accelerate the testing with multiple GPUs you might need to change the code according to the [train.py](https://github.com/Algolzw/daclip-uir/blob/main/universal-image-restoration/config/daclip-sde/train.py).

**Comment by gorgeousmwz** [comment]
Thank you very much
