### ISSUE TITLE
How do you integrate DA-CLIP to NAFNet?

### ISSUE THREAD

**Issue by zinuoli** [Algolzw/daclip-uir#44]
Hi, very appreciate your open-source work and it gives us great insights.

I noticed that in the page 7 of your paper it mentions: "Moreover, we further integrate1 DA-CLIP into an MSE-based network NAFNet (Chen et al., 2022) as a variant of our method.", may I know how do you implement it since there is no cross-attention modules in NAFNet?

Thank you so much and wish you have a bright future on your research path.

**Comment by Algolzw** [comment]
Hi! For NAFNet, we add additional cross-attentions in the bottom layer similar to the denoising U-Net ([this line](https://github.com/Algolzw/daclip-uir/blob/84a6ab6185bb7af9acacef88542411893bcb3ec6/universal-image-restoration/config/daclip-sde/models/modules/DenoisingUNet_arch.py#L103)).

**Comment by zinuoli** [comment]
Thank you for much for your quick reply😄

**Comment by Algolzw** [comment]
No worries at all. :)

I train them separately (first train DACLIP then IR model).

**Comment by MADAOOOOO** [comment]
hi, I read the description of how to integrate DA-CLIP and NAFNet in the paper. But I still don't know how to do it. 
May i know how do you  combine with NAFBlock after obtaining prompt embedding.And 'use cross attention in the bottom layers',do you mean add a addtional cross-attention in he NAFBlock of the bottom layers or replace the SCA in the NAFBlock?Thanks a lot!

**Comment by zinuoli** [comment]
@MADAOOOOO This kind author has replied my here [#45](https://github.com/Algolzw/daclip-uir/issues/45).

**Comment by MADAOOOOO** [comment]
@zinuoli Thank you so much .it helps me a lot.
