### ISSUE TITLE
snowy train set selection.

### ISSUE THREAD

**Issue by zhangxinkang** [Algolzw/daclip-uir#49]
Hello, in order to reproduce the training process, I would like to ask you how you selected the 1872 training sets and 601 test sets from 100k snowy pictures. It would be great if you could give a sample list. Thank you again for sharing your excellent research results.

best wishes

**Comment by Algolzw** [comment]
Hej, we use images with names containing `beautiful_smile`. For convenience, we upload the desnowing training data to this [google drive](https://drive.google.com/file/d/11Cnnj8SK9RIpZEf2wIOwVoR0-LTMfE_j/view?usp=sharing). And all validation datasets can be downloaded [here](https://drive.google.com/file/d/1JKd1tA7rMoEbI9190daJqL7i6V1L8KUd/view?usp=sharing).
