### ISSUE TITLE
Cannot Generate Clean Captions With BLIP  

### ISSUE THREAD

**Issue by gejutaixiao22** [Algolzw/daclip-uir#61]
Traceback (most recent call last):
  File "./scripts/generate_captions.py", line 73, in <module>
    ci = Interrogator(Config(clip_model_name="./laion/openai3"))
  File "/root/autodl-tmp/daclip-uir-main/.env/lib/python3.8/site-packages/clip_interrogator/clip_interrogator.py", line 70, in __init__
    self.load_caption_model()
  File "/root/autodl-tmp/daclip-uir-main/.env/lib/python3.8/site-packages/clip_interrogator/clip_interrogator.py", line 84, in load_caption_model
    caption_model = BlipForConditionalGeneration.from_pretrained(model_path, torch_dtype=self.dtype)
  File "/root/autodl-tmp/daclip-uir-main/.env/lib/python3.8/site-packages/transformers/modeling_utils.py", line 3235, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/root/autodl-tmp/daclip-uir-main/.env/lib/python3.8/site-packages/transformers/configuration_utils.py", line 603, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/root/autodl-tmp/daclip-uir-main/.env/lib/python3.8/site-packages/transformers/configuration_utils.py", line 632, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/root/autodl-tmp/daclip-uir-main/.env/lib/python3.8/site-packages/transformers/configuration_utils.py", line 689, in _get_config_dict
    resolved_config_file = cached_file(
  File "/root/autodl-tmp/daclip-uir-main/.env/lib/python3.8/site-packages/transformers/utils/hub.py", line 445, in cached_file
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like Salesforce/blip-image-captioning-large is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

Could you please provide the link to download the weights and where to put them? Thank you very much

**Comment by zw-absin** [comment]
打扰一下啊，请问您最后是怎么解决这个问题的，我该去哪手动下载一个权重到 cached files吗？

**Comment by zw-absin** [comment]
> Traceback (most recent call last): File "./scripts/generate_captions.py", line 73, in ci = Interrogator(Config(clip_model_name="./laion/openai3")) File "/root/autodl-tmp/daclip-uir-main/.env/lib/python3.8/site-packages/clip_interrogator/clip_interrogator.py", line 70, in **init** self.load_caption_model() File "/root/autodl-tmp/daclip-uir-main/.env/lib/python3.8/site-packages/clip_interrogator/clip_interrogator.py", line 84, in load_caption_model caption_model = BlipForConditionalGeneration.from_pretrained(model_path, torch_dtype=self.dtype) File "/root/autodl-tmp/daclip-uir-main/.env/lib/python3.8/site-packages/transformers/modeling_utils.py", line 3235, in from_pretrained config, model_kwargs = cls.config_class.from_pretrained( File "/root/autodl-tmp/daclip-uir-main/.env/lib/python3.8/site-packages/transformers/configuration_utils.py", line 603, in from_pretrained config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs) File "/root/autodl-tmp/daclip-uir-main/.env/lib/python3.8/site-packages/transformers/configuration_utils.py", line 632, in get_config_dict config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs) File "/root/autodl-tmp/daclip-uir-main/.env/lib/python3.8/site-packages/transformers/configuration_utils.py", line 689, in _get_config_dict resolved_config_file = cached_file( File "/root/autodl-tmp/daclip-uir-main/.env/lib/python3.8/site-packages/transformers/utils/hub.py", line 445, in cached_file raise EnvironmentError( OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like Salesforce/blip-image-captioning-large is not the path to a directory containing a file named config.json. Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.
> 
> Could you please provide the link to download the weights and where to put them? Thank you very much

打扰一下啊，请问您最后是怎么解决这个问题的，我该手动下载一个权重到 cached files吗，下面的都要用到吗？
CAPTION_MODELS = {
    'blip-base': 'Salesforce/blip-image-captioning-base',   # 990MB
    'blip-large': 'Salesforce/blip-image-captioning-large', # 1.9GB
    'blip2-2.7b': 'Salesforce/blip2-opt-2.7b',              # 15.5GB
    'blip2-flan-t5-xl': 'Salesforce/blip2-flan-t5-xl',      # 15.77GB
    'git-large-coco': 'microsoft/git-large-coco',           # 1.58GB
}
CACHE_URL_BASE = 'https://huggingface.co/pharma/ci-preprocess/resolve/main/'
