### ISSUE TITLE
test problem

### ISSUE THREAD

**Issue by Feecuin** [Algolzw/daclip-uir#82]
作者您好，我想问下您这个权重可以测其他数据集的图片吗？例如其他含雨或者含雾数据集

**Comment by Algolzw** [comment]
你可以试一下，你可以使用这里Universal-IR-mix的[weight](https://github.com/Algolzw/daclip-uir?tab=readme-ov-file#pretrained-models)。

**Comment by Feecuin** [comment]
> 你可以试一下，你可以使用这里Universal-IR-mix的[权重](https://github.com/Algolzw/daclip-uir?tab=readme-ov-file#pretrained-models)。

您好，我还有一个问题想问问，您的代码里config中只有daclip-sde和wild-ir，是否是使用daclip-sde测试呢？

**Comment by Algolzw** [comment]
是的哈
