### ISSUE TITLE
作者您好，我想请问几个关于daclip的问题

### ISSUE THREAD

**Issue by LiJiajun000322** [Algolzw/daclip-uir#84]
Q1：daclip的diffusion模型(ir-sde)是基于您论文提供的那些数据集进行训练吗？假设我只想做低光增强任务，是否仅仅使用LOL数据集（其他的去雨等数据集都可以不使用）就能训练好IR-SDE吗？

**Comment by LiJiajun000322** [comment]
Q2:请问当时为什么不选用预训练好的扩散模型，修改他的输入输出、优化目标等从而获得更好的图像重建效果呢？而是选择重新训练一个扩散模型？

**Comment by LiJiajun000322** [comment]
Q3：ir-sde为什么选择在像素空间进行扩散呢，为什么不选择在潜在空间进行扩散呢？
感谢作者提供的工作！

**Comment by Algolzw** [comment]
你好，1）只用LOL数据是可以训练IR-SDE的，其对数据数量的要求并不高。2）理论上当然也可以使用预训练的diffusion模型，但大部分预训练模型更偏向于保证生成的质量而不能保证输入输出的一致性，比如有可能发生骗色啊或者细节不一致等，即PSNR/SSIM很低。3）latent space diffusion也是可以的哈，不过其结果也取决于VAE的质量，也容易发生输入输出不一致的现象。
这些很多都是不好解决的问题，da-clip主要目的之一是为了引入CLIP的embedding来提升图像生成质量和一致性，而使用预训练以及latent模型都确实是可以作为改进的方向。

**Comment by LiJiajun000322** [comment]
非常感谢您的回答！我还想继续请教一点问题
Q1：IR-SDE里的源码当时是没有给出低光增强方向的，如果我想训练一个低光增强方向的IR-SDE，直接用其他方向（如去雨等）进行迁移训练可以吗？
Q2：您有提到说daclip主要目的之一是用CLIP的编码器作为扩散模型的控制，那如果我直接用经过BLIP获得的LQ的图文对作为输入，经过CLIP编码作为控制信号去控制扩散过程，生成质量上是否有太大差异呢
Q3：我想请问一些理论方面的问题，我不是很能搞懂DDPM、DDIM和SDE的关系，SDE是否就是一个数学过程呢，然后DDPM和DDIM分别是这个具体过程的实现？

**Comment by LiJiajun000322** [comment]
另外还有一个问题请您指教，据了解训练一个扩散模型应该是需要非常大的数据量的，为什么在IR-SDE里，仅用一个几百张的数据集就能训练好呢？

**Comment by Algolzw** [comment]
感觉这取决于任务。经验上来说，相对unconditional图像生成，普通图像复原更简单一点：LQ和HQ差距通常不大且配对良好，因此对数据的需求其实并不大。对一些任务如超分，即使增加大量图像数据，生成质量的提升依旧有限。

**Comment by LiJiajun000322** [comment]
非常感谢您的回答！我还想继续请教一点问题
Q1：IR-SDE里的源码当时是没有给出低光增强方向的，如果我想训练一个低光增强方向的IR-SDE，直接用其他方向（如去雨等）进行迁移训练可以吗？
Q2：您有提到说daclip主要目的之一是用CLIP的编码器作为扩散模型的控制，那如果我直接用经过BLIP获得的LQ的图文对作为输入，经过CLIP编码作为控制信号去控制扩散过程，生成质量上是否有太大差异呢
Q3：我想请问一些理论方面的问题，我不是很能搞懂DDPM、DDIM和SDE的关系，SDE是否就是一个数学过程呢，然后DDPM和DDIM分别是这个具体过程的实现？

**Comment by Algolzw** [comment]
1. 迁移训练是指用pretrained的weight吗？如果这样最好使用使用比较general的模型比如DA-CLIP里的IR-SDE。2. 我们实验是发现输入LQ 原始embedding的话效果会差一点，最好是从embedding里移除degradation信息。3. SDE其实可以看作一个把离散的加噪连续化的过程，DDPM其实是SDE一种离散化的solution，而DDIM是SDE对应的ODE（也就是去掉噪声的部分）采样。可以参考这本书：Applied Stochastic Differential Equations.

**Comment by LiJiajun000322** [comment]
非常感谢！

**Comment by LiJiajun000322** [comment]
如果我只想训练一个用于低光增强任务的ir-sde，可以直接用daclip-sde里的训练参数吗，或者能否请您提供一下IR-SDE关于低光增强任务的具体参数

**Comment by Algolzw** [comment]
可以直接用这里的：https://github.com/Algolzw/daclip-uir/blob/main/universal-image-restoration/config/daclip-sde/options/test.yml

**Comment by LiJiajun000322** [comment]
好的！非常感谢
